version: "3"
services:
    database:
        image: "postgres"
        container_name: "database"
        network_mode: host
        env_file:
          - ./infrastructure/database.env
        volumes:
          - ./infrastructure/initialize-databases.sql:/docker-entrypoint-initdb.d/init.sql
    monitoring:
        image: "prom/prometheus"
        container_name: "prometheus"
        network_mode: host
        volumes:
          - ./infrastructure/prometheus.yml:/etc/prometheus/prometheus.yml
    api-gateway:
        image: "quarkus/api-gateway-jvm"
        network_mode: host
    book-service:
        image: "quarkus/book-service-jvm"
        network_mode: host
        depends_on:
          - database
    borrow-service:
        image: "quarkus/borrow-service-jvm"
        network_mode: host
        depends_on:
          - database
    user-service:
        image: "quarkus/user-service-jvm"
        network_mode: host
        depends_on:
          - database
    grafana:
        image: grafana/grafana:6.4.4
        container_name: grafana
        network_mode: host

    jaeger:
        image: jaegertracing/all-in-one:1.21.0
        container_name: jaeger
        ports:
          - "5775:5775/udp"
          - "6831:6831/udp"
          - "6832:6832/udp"
          - "5778:5778"
          - "16686:16686"
          - "14268:14268"
