global:
  scrape_interval: 15s

# tag::adocPrometheus[]
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['localhost:8080']
  - job_name: 'book-service'
    static_configs:
      - targets: ['localhost:8081']
  - job_name: 'borrow-service'
    static_configs:
      - targets: ['localhost:8082']
  - job_name: 'user-service'
    static_configs:
      - targets: ['localhost:8083']
# end::adocPrometheus[]
